# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: midas/midas.proto

require 'google/protobuf'

require 'proto/midas/midas_message_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file('midas/midas.proto', syntax: :proto3) do
  end
end

module Midas
end
