# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: midas/midas.proto for package 'midas'

require 'grpc'
require 'proto/midas/midas_pb'

module Midas
  module MidasService
    class Service
      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'midas.MidasService'

      rpc :GetText, GetTextRequest, stream(GetTextResponse)
      rpc :GetImages, GetImagesRequest, stream(GetImagesResponse)
    end

    Stub = Service.rpc_stub_class
  end
end
